- composer.json
- monorepo-builder.php
- src/Snicco/Component/better-wp-hooks/composer.json
- src/Snicco/Component/eloquent/composer.json
- src/Snicco/Component/scopable-wp/composer.json
- src/Snicco/Component/wp-object-cache-psr16/composer.json
see: https://github.com/lucatume/wp-browser/pull/561
> root: update wp-browser-version to 3.1.3 to support pslam

- src/Snicco/Bundle/http-routing/src/HttpRoutingBundle.php
- src/Snicco/Component/http-routing/src/Routing/Condition/NewableRouteConditionFactory.php
- src/Snicco/Component/http-routing/src/Routing/Condition/RouteConditionFactory.php
- src/Snicco/Component/http-routing/src/Routing/Router.php
- src/Snicco/Component/http-routing/src/Routing/UrlMatcher/FastRouteDispatcher.php
- src/Snicco/Component/http-routing/tests/HttpRunnerTestCase.php
- src/Snicco/Component/http-routing/tests/Routing/RouterTest.php
- src/Snicco/Component/http-routing/tests/Routing/UrlMatcher/RouteActionDependencyInjectionTest.php
- src/Snicco/Component/http-routing/tests/Routing/UrlMatcher/RouteConditionsTest.php
- src/Snicco/Component/http-routing/tests/fixtures/Conditions/RouteConditionWithArgs.php
The Router class now accepts an optional interface for the RouteConditionFactory.php. The Router now has the correct dependencies instead of relying on a psr container instance.
If resolving conditions via a psr 3 container is desired this can be implemented in user land.
> component/http-routing: make RouteConditionFactory.php an interface.

- src/Snicco/Bridge/signed-url-middleware/tests/ValidateSignatureTest.php
- src/Snicco/Bundle/session/tests/Middleware/SessionNoCacheTest.php
- src/Snicco/Bundle/session/tests/Middleware/ShareSessionWithViewsTest.php
- src/Snicco/Bundle/session/tests/Middleware/StatefulRequestTest.php
- src/Snicco/Component/http-routing/testing/AssertableCookie.php
- src/Snicco/Component/http-routing/testing/MiddlewareTestCase.php
- src/Snicco/Component/http-routing/testing/MiddlewareTestResult.php
- src/Snicco/Component/http-routing/tests/Testing/AssertableCookieTest.php
- src/Snicco/Component/http-routing/tests/Testing/MiddlewareTestCaseTest.php
- src/Snicco/Middleware/default-headers/tests/DefaultHeadersTest.php
- src/Snicco/Middleware/https-only/tests/HttpsOnlyTest.php
- src/Snicco/Middleware/must-match-route/tests/MustMatchRouteTest.php
- src/Snicco/Middleware/negotiation/tests/NegotiateContentTest.php
- src/Snicco/Middleware/no-robots/tests/NoRobotsTest.php
- src/Snicco/Middleware/open-redirect-protection/tests/OpenRedirectProtectionTest.php
- src/Snicco/Middleware/redirect/tests/RedirectTest.php
- src/Snicco/Middleware/share-cookies/tests/ShareCookiesTest.php
- src/Snicco/Middleware/trailing-slash/tests/TrailingSlashTest.php
- src/Snicco/Middleware/wp-guests-only/tests/GuestsOnlyTest.php
- src/Snicco/Middleware/wp-nonce/tests/VerifyWPNonceTest.php
MiddlewareTestResponse.php is now named MiddlewareTestResult.php
> component/http-routing: tests for missing todos

- .github/workflows/split_monorepo.yaml
We need composer in order to publish packages at GitHub and packagist.
> Install composer deps before splitting monorepo

- .github/workflows/split_monorepo.yaml
Adds a 3s timeout after GitHub repos are created and after the repo is split.
> split_monorepo.yaml: sleep between repo-creation

- .github/workflows/code_analysis.yaml
- .github/workflows/code_coverage.yaml
- .github/workflows/tests.yaml
The time for CI/CD runs became pretty large especially if non-src files like READMEs are changed. This commit modifies the tests, code-analysis, and coverage workflow so that they only run if relevant files are modified. For this, we use the GitHub action https://github.com/dorny/paths-filter.
> chore(root): Run workflows conditionally based on changed files

- .github/workflows/code_coverage.yaml
- .github/workflows/psalm.yaml
- .github/workflows/release.yaml
- .github/workflows/static_analysis.yaml
- .github/workflows/tests.yaml
The release.yaml workflow and the psalm.yaml workflow contained invalid syntax.
> ci(monorepo): fix yaml syntax in workflows

- .github/workflows/code_coverage.yaml
- codecov.yml
- phpunit.xml.dist
The directories were hardcoded previously
so that merging #101 caused the coverage
for all testing classes to disappear
> ci(monorepo): include the testing directory in codecov

- .github/workflows/code_coverage.yaml
We need to get a passing commit into master.
Currently, every commit into master will fail
coverage for the same "missing head" reason.
> ci(monorepo): disable codecov temporarily

- .github/workflows/code_coverage.yaml
- codecov.yml
Set if_not_found to false in codecov.yml
This allows as to upload coverage
conditionally only if source code
changed.
> ci(monorepo): run code coverage workflow conditionally

- .github/workflows/code_coverage.yaml
- codecov.yml
Send coverage to codecov.io for all PRs.
After trying every possible configuration
of settings,
it's not worth it to upload conditionally,
as CI status will not be sent back
from codecov.io if no coverage is uploaded.
Fixes: #92
See: https://community.codecov.com/t/how-to-make-codecov-branch-status-checks-conditional/3549
> ci(monorepo): run codecov for all pull requests

- .releaserc.js
Including skip-ci in the commit message will prevent
the monorepo-split workflow from running.
Fix: #124
> ci(monorepo): remove [skip-ci] check in release commit name

- codecov.yml
This fixes the "No coverage found on head"
message in all coverage checks.
> ci(monorepo): fix codecov.yml path settings

- src/Snicco/Component/better-wpdb/README.md
- src/Snicco/Component/better-wpdb/codeception.dist.yml
- src/Snicco/Component/better-wpdb/src/BetterWPDB.php
- src/Snicco/Component/better-wpdb/tests/wordpress/BetterWPDB_exceptions_Test.php
- src/Snicco/Component/better-wpdb/tests/wordpress/BetterWPDB_safeQuery_Test.php
By default, mysqli prepared statements are using unbuffered
queries. This means that we can not reset the error
handling before the statement result is released
by either calling $stmt->store_result() or $stmt->getResult().
This seemed to never have worked in the first place for select queries.
Inserts, deletes etc. are not effected because they don't
return a result set.
See: https://www.php.net/manual/de/mysqlinfo.concepts.buffering.php
See: https://stackoverflow.com/a/614741
> fix(better-wpdb): fix error handling reset with unbuffered queries

- src/Snicco/Bundle/testing/codeception.dist.yml
- src/Snicco/Bundle/testing/composer.json
- src/Snicco/Bundle/testing/src/Functional/Browser.php
- src/Snicco/Bundle/testing/tests/wordpress/Functional/BrowserTest.php
- src/Snicco/Bundle/testing/tests/wordpress/fixtures/WebTestCaseController.php
- src/Snicco/Bundle/testing/tests/wordpress/fixtures/routes/frontend.php
The Browser class had some missing pieces in the
code that transforms the Symfony Browserkit response
into a PSR7 response.
In particular, HTTP_XXX and CONTENT_XXX server params
were not transformed to headers in the PSR7 request.
Furthermore, request were marked as API requests
if the API prefix in the configuration was "/".
Fix: #140
Fix: #141
> fix(testing-bundle): fix request generation of test browser

- composer.json
- src/Snicco/Middleware/wp-nonce/src/VerifyWPNonce.php
- src/Snicco/Middleware/wp-nonce/tests/VerifyWPNonceTest.php
Previously an instance of WPNonce was only added to ViewResponses returned for READ requests.
Fix: #155
> fix(wp-nonce-middleware): add nonce factory to all view responses

- composer-require-checker.json
- src/Snicco/Bundle/http-routing/src/HttpKernelRunner.php
- src/Snicco/Bundle/http-routing/tests/wordpress/HttpKernelRunnerTest.php
WordPress will still completely nuke the request variables by slashing them with wp_magic_quotes().
There is an open ticket for this since 10+ years, but we suppose it will never get fixed.
With the http-routing-bundle we are always getting the real server variables, but this change ensures and enforces this.
See: https://core.trac.wordpress.org/ticket/18322
> fix(http-routing-bundle): enforce request data is not slashed

- README.md
Fixes a broken link to the `wp-capability-middleware` repo in `README.md`.
> docs(monorepo): fix broken link in `README.md`

- .github/workflows/code_coverage.yaml
- .github/workflows/release.yaml
- .gitignore
- .releaserc.js
- src/Snicco/Component/kernel/src/ValueObject/Directories.php
- src/Snicco/Component/kernel/tests/ValueObject/DirectoriesTest.php
BREAKING CHANGE: Previously creating an instance of the kernel class always asserted that cache/log/config dirs are
readable.
This created a lot of development complexities as these directories always had to be pre-created before a kernel instance could be created. It also creates runtime overhead for little additional safety. There is no way to ensure that a directory did not go missing between Directories::__construct(), and the usage of any directory. Callers of the Directory class are now responsible for error handling, as they should always have.
> fix(kernel): don't check if directories are readable in constructor

- src/Snicco/Bundle/http-routing/src/MiddlewareCache.php
- src/Snicco/Component/http-routing/src/Routing/Cache/FileRouteCache.php
- src/Snicco/Component/kernel/src/Configuration/PHPFileCache.php
BREAKING CHANGE:
all cache directories are created with 0700
permissions and all files with 0600.
Previously, they were created with 0755/0644.
> feat(*): stricter directory permissions for all cache files

- composer.json
`simplify/monorepo-builder` does not work
well with semantic release as soon
as there are multiple branches because
it compares versions based
on creation date only.
Monorepo builder shall just tag whatever
semantic release provides!
> fix(*): use fork of simplify/monorepo-builder
